# ------------------------------------------------------------------------------
# The deployment file considers master node also for targetting deployments
# The following command needs to be set into both master node and worker nodes
# kubectl label node k8s-master kubernetes.io/system-apis=allow
# ------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airports-locator-app
spec:
  selector:
      matchLabels:
        app: airports-locator-app
  replicas: 1
  template:
    metadata:
      labels:
        app: airports-locator-app
    spec:
      nodeSelector:
        kubernetes.io/system-apis: allow
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - airports-locator-app
            topologyKey: "kubernetes.io/hostname"
      # ----------------------------------
      # will target master node deployment
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      # ----------------------------------
      containers:
        - name: airports-locator-app
          image: srivatsabc/airports-locator-app:system-api-v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            - name: RUNTIME.ENV.TYPE #In order to help mule application pickup the right jdbc properties
              valueFrom:
                configMapKeyRef:
                  name: airports-locator-app-config
                  key: RUNTIME.ENV.TYPE
